cfg = {
    'class_rehearsal': {
        'which_data': 'class_rehearsal',
        'dimension': 1582,
        'DATA_NAME': '../raw_data/class_rehearsal/',
        'train_df_name': 'raw_data_3833.csv',
        'valid_df_name': 'raw_data_3833.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '*-1.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['情感丰富'],
        'negative_label_types': ['情感一般'],
    },
    'peiyou_conclude': {
        'which_data': 'peiyou_conclude',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/peiyou_conclude/',
        'train_df_name': 'raw_data_1500.csv',
        'valid_df_name': 'raw_data_1500.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '7203-培优总结-卓思维-*.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['1'],
        'negative_label_types': ['0'],
    },
    'peiyou_praise': {
        'which_data': 'peiyou_praise',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/peiyou_praise/',
        'train_df_name': 'raw_data_1500.csv',
        'valid_df_name': 'raw_data_1500.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '7203-培优鼓励-卓思维-*.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['1'],
        'negative_label_types': ['0'],
    },
    'question_detection': {
        'which_data': 'question_detection',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/question_detection/',
        'train_df_name': 'train_raw_3925.csv',
        'valid_df_name': 'train_raw_3925.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '*-1.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['评估问句', '认知问句', '其它问句', '自问自答问句'],
        'negative_label_types': ['无人声', '非提问'],
    },
    'fluency_128': {
        'which_data': 'fluency_128',
        'dimension': 128,
        'DATA_NAME': '../raw_data/fluency_128/',
        'train_df_name': 'train_raw_4198.csv',
        'valid_df_name': 'train_raw_4198.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '7763*.json',
        'positive_label_types': ['流利'],
        'negative_label_types': ['不流利'],
    },
    'question_detection_rand_2_flip_0': {
        'which_data': 'question_detection_rand_2_flip_0',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/simu_data/question_detection_rand_2_flip_0/',
        'train_df_name': 'train_raw_3925.csv',
        'valid_df_name': 'train_raw_3925.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '*-1.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['评估问句', '认知问句', '其它问句', '自问自答问句'],
        'negative_label_types': ['无人声', '非提问'],
    },
    'question_detection_rand_4_flip_0': {
        'which_data': 'question_detection_rand_4_flip_0',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/simu_data/question_detection_rand_4_flip_0/',
        'train_df_name': 'train_raw_3925.csv',
        'valid_df_name': 'train_raw_3925.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '*-1.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['评估问句', '认知问句', '其它问句', '自问自答问句'],
        'negative_label_types': ['无人声', '非提问'],
    },
    'question_detection_rand_6_flip_0': {
        'which_data': 'question_detection_rand_6_flip_0',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/simu_data/question_detection_rand_6_flip_0/',
        'train_df_name': 'train_raw_3925.csv',
        'valid_df_name': 'train_raw_3925.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '*-1.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['评估问句', '认知问句', '其它问句', '自问自答问句'],
        'negative_label_types': ['无人声', '非提问'],
    },
    'question_detection_rand_8_flip_0': {
        'which_data': 'question_detection_rand_8_flip_0',
        'dimension': 1024,
        'DATA_NAME': '../raw_data/simu_data/question_detection_rand_8_flip_0/',
        'train_df_name': 'train_raw_3925.csv',
        'valid_df_name': 'train_raw_3925.csv',
        'test_df_name': 'test.csv',
        'json_file_pattern': '*-1.json',
        'label_details_df': 'label_details.csv',
        'positive_label_types': ['评估问句', '认知问句', '其它问句', '自问自答问句'],
        'negative_label_types': ['无人声', '非提问'],
    },
}